name: 🚀 Prod Deployment

on:
  push:
    branches:
      - dev

concurrency:
  group: dev
  cancel-in-progress: true

jobs:
  deploy-api:
    uses: ./.github/workflows/_shared_service_golang_app.yml
    with:
      ENV: prod
      GO_APP_PATH: apps/backend/cmd/serverless
      DEPLOY_PATH: apps/backend/infra/deploy
      BRANCH: dev
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
      CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}