name: Frontend CI/CD

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/web/**'
      - '.github/workflows/web-frontend-ci.yml'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'apps/web/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint frontend code
        run: |
          cd apps/web
          npm run lint

      - name: Type check frontend
        run: |
          cd apps/web
          npm run typecheck

      - name: Run tests
        run: |
          cd apps/web
          npm run test:run

      - name: Build frontend
        run: |
          cd apps/web
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: apps/web/dist
          retention-days: 7

      - name: Upload build stats (if available)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-stats
          path: apps/web/dist/stats.html
          retention-days: 7
        continue-on-error: true

  # Optional: Deploy step (uncomment when ready for deployment)
  # deploy:
  #   needs: build-and-test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main'
  #   
  #   steps:
  #     - name: Download build artifacts
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: frontend-dist
  #         path: dist
  #     
  #     - name: Deploy to hosting service
  #       # Add deployment steps here (Netlify, Vercel, etc.)
  #       run: echo "Deploy step - configure based on hosting provider"
